name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - CANT_CLIENTES=5
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Lionel Andres
      - APELLIDO=Messi
      - DOCUMENTO=106998
      - FECHA_NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./.data/agency-1.csv:/bets.csv
      - ./client/config.yaml:/config.yaml

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Lionel Andres
      - APELLIDO=Messi
      - DOCUMENTO=106998
      - FECHA_NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./.data/agency-2.csv:/bets.csv
      - ./client/config.yaml:/config.yaml

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Lionel Andres
      - APELLIDO=Messi
      - DOCUMENTO=106998
      - FECHA_NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./.data/agency-3.csv:/bets.csv
      - ./client/config.yaml:/config.yaml

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Lionel Andres
      - APELLIDO=Messi
      - DOCUMENTO=106998
      - FECHA_NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./.data/agency-4.csv:/bets.csv
      - ./client/config.yaml:/config.yaml

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Lionel Andres
      - APELLIDO=Messi
      - DOCUMENTO=106998
      - FECHA_NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./.data/agency-5.csv:/bets.csv
      - ./client/config.yaml:/config.yaml

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
